"""add column updated_by

Revision ID: 8987e3c2154c
Revises: 7350837e000b
Create Date: 2021-12-27 13:33:34.083106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8987e3c2154c'
down_revision = '7350837e000b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compressors', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'compressors', 'data_entries', ['updated_by'], ['pk'])
    op.add_column('electricity', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'electricity', 'data_entries', ['updated_by'], ['pk'])
    op.add_column('natural_gas', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'natural_gas', 'data_entries', ['updated_by'], ['pk'])
    op.add_column('water', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'water', 'data_entries', ['updated_by'], ['pk'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'water', type_='foreignkey')
    op.drop_column('water', 'updated_by')
    op.drop_constraint(None, 'natural_gas', type_='foreignkey')
    op.drop_column('natural_gas', 'updated_by')
    op.drop_constraint(None, 'electricity', type_='foreignkey')
    op.drop_column('electricity', 'updated_by')
    op.drop_constraint(None, 'compressors', type_='foreignkey')
    op.drop_column('compressors', 'updated_by')
    # ### end Alembic commands ###
