"""add users tables

Revision ID: b160ef6078ee
Revises: 3f8e1bd9d52b
Create Date: 2021-12-10 22:03:48.445691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b160ef6078ee'
down_revision = '3f8e1bd9d52b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CEO',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('unknown', 'bulgargaz', 'energo_pro', 'data_entry', 'data_analyst', 'accountant', 'ceo', name='roletype'), nullable=False),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('email')
    )
    op.create_table('accountants',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('unknown', 'bulgargaz', 'energo_pro', 'data_entry', 'data_analyst', 'accountant', 'ceo', name='roletype'), nullable=False),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('email')
    )
    op.create_table('data_analysts',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('unknown', 'bulgargaz', 'energo_pro', 'data_entry', 'data_analyst', 'accountant', 'ceo', name='roletype'), nullable=False),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('email')
    )
    op.create_table('data_entries',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('unknown', 'bulgargaz', 'energo_pro', 'data_entry', 'data_analyst', 'accountant', 'ceo', name='roletype'), nullable=False),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('email')
    )
    op.create_table('payment_receivers',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('iban', sa.String(length=22), nullable=False),
    sa.Column('role', sa.Enum('unknown', 'bulgargaz', 'energo_pro', 'data_entry', 'data_analyst', 'accountant', 'ceo', name='roletype'), nullable=False),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('email')
    )
    op.add_column('compressors', sa.Column('data_entry_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'compressors', 'data_entries', ['data_entry_id'], ['pk'])
    op.add_column('electricity', sa.Column('data_entry_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'electricity', 'data_entries', ['data_entry_id'], ['pk'])
    op.add_column('natural_gas', sa.Column('data_entry_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'natural_gas', 'data_entries', ['data_entry_id'], ['pk'])
    op.add_column('water', sa.Column('data_entry_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'water', 'data_entries', ['data_entry_id'], ['pk'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'water', type_='foreignkey')
    op.drop_column('water', 'data_entry_id')
    op.drop_constraint(None, 'natural_gas', type_='foreignkey')
    op.drop_column('natural_gas', 'data_entry_id')
    op.drop_constraint(None, 'electricity', type_='foreignkey')
    op.drop_column('electricity', 'data_entry_id')
    op.drop_constraint(None, 'compressors', type_='foreignkey')
    op.drop_column('compressors', 'data_entry_id')
    op.drop_table('payment_receivers')
    op.drop_table('data_entries')
    op.drop_table('data_analysts')
    op.drop_table('accountants')
    op.drop_table('CEO')
    # ### end Alembic commands ###
