"""add payment requests table

Revision ID: b8462c00f8b0
Revises: ac0c693d0d5e
Create Date: 2022-01-08 19:12:55.409161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8462c00f8b0'
down_revision = 'ac0c693d0d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_requests',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['payment_receivers.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_requests')
    # ### end Alembic commands ###
