"""empty message

Revision ID: f98aaa6b502a
Revises: 
Create Date: 2021-12-09 21:05:03.930378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f98aaa6b502a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compressors',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('kwh', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('electricity',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('kwh', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('natural_gas',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('Nm3', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('water',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('m3', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water')
    op.drop_table('natural_gas')
    op.drop_table('electricity')
    op.drop_table('compressors')
    # ### end Alembic commands ###
